const assert = require('assert/strict'); const Module = require('module'); const path = require('path');
const fs = require('fs');
const frequentTemplate = fs.readFileSync(path.resolve(__dirname, '../miniapp/package-business/pages/frequent/index.wxml'), 'utf8');
assert.match(frequentTemplate, /wx:elif="\{\{status == 'forbidden'\}\}"[^>]*><text>仅企业采购账户可用<\/text><text>\{\{errorText\}\}<\/text><button bindtap="back">返回<\/button>/, 'the forbidden state must describe business eligibility and label navigateBack truthfully');
assert.doesNotMatch(frequentTemplate, /返回登录/, 'a back action must not promise to open login');
const originalLoad = Module._load; const pages = []; const batchCalls = []; const commitCalls = []; const toasts = [];
const services = { auth: { getMe: async () => ({ ok: true, data: { user: { userType: 'b', businessStatus: 'approved', organizationId: 'org-1', status: 'active' } } }) }, catalog: { listAllProducts: async () => ({ ok: true, data: { rows: [{ _id: 'p1', name: '鱼丸', skus: [{ _id: 'sku-1', specName: '500g', minOrderQuantity: 3, orderMultiple: 2 }] }] } }), listPrices: async () => ({ ok: true, data: { rows: [{ skuId: 'sku-1', amountCent: 1800, minOrderQuantity: 3, orderMultiple: 2 }] } }) }, frequent: { list: async () => ({ ok: true, data: { rows: [{ _id: 'f1', skuId: 'sku-1', quantity: 4 }] } }), batchAddToCart: async payload => { batchCalls.push(payload); return { ok: true, data: { addedItems: [{ skuId: 'sku-1' }], invalidItems: [{ skuId: 'sku-x', message: '已下架' }] } }; } }, orders: { repurchasePreview: async () => ({ ok: true, data: { addedItems: [{ skuId: 'sku-1', quantity: 4, unitPriceCent: 1800 }], invalidItems: [{ skuId: 'sku-2', message: '已下架' }] } }), repurchaseCommit: async payload => { commitCalls.push(payload); return { ok: true, data: { addedItems: [{ skuId: 'sku-1' }], invalidItems: [] } }; } } };
Module._load = function (request, parent, isMain) { if (request === '../../../services/index') return services; return originalLoad.call(this, request, parent, isMain); }; global.Page = definition => pages.push(definition); global.wx = { showToast: payload => toasts.push(payload), reLaunch: () => {}, navigateBack: () => {} };
try { require(path.resolve(__dirname, '../miniapp/package-business/pages/frequent/index.js')); require(path.resolve(__dirname, '../miniapp/package-business/pages/repurchase/index.js')); } finally { Module._load = originalLoad; delete global.Page; }
const makePage = definition => Object.assign({}, definition, { data: JSON.parse(JSON.stringify(definition.data)), setData(patch) { Object.assign(this.data, patch); } });
async function run() { const frequent = makePage(pages[0]); await frequent.load(); assert.equal(frequent.data.rows[0].quantity, 4); frequent.changeQuantity({ currentTarget: { dataset: { id: 'f1', direction: 1 } }, detail: {} }); assert.equal(frequent.data.rows[0].quantity, 6); frequent.changeQuantity({ currentTarget: { dataset: { id: 'f1' } }, detail: { source: 'input', valid: true, quantity: 10 } }); assert.equal(frequent.data.rows[0].quantity, 10, '常购数量必须支持合法数字直输'); frequent.changeQuantity({ currentTarget: { dataset: { id: 'f1' } }, detail: { source: 'input', valid: false, message: '数量须为 2 的倍数' } }); assert.equal(frequent.data.rows[0].quantity, 10, '非法直输不能改变常购数量'); assert.equal(toasts.at(-1).title, '数量须为 2 的倍数'); await frequent.batchAdd(); assert.deepEqual(batchCalls[0].ids, ['f1']); assert.equal(batchCalls[0].items[0].id, 'f1'); assert.equal(batchCalls[0].items[0].quantity, 10); assert.equal(frequent.data.invalidItems[0].message, '已下架'); const repurchase = makePage(pages[1]); repurchase.data.orderId = 'order-1'; await repurchase.load(); assert.equal(repurchase.data.rows.length, 1); assert.equal(repurchase.data.invalidItems.length, 1); await repurchase.commit(); assert.equal(commitCalls[0].orderId, 'order-1'); assert.equal(repurchase.data.addedItems.length, 1); console.log('b2b frequent and repurchase test: passed'); }
run().catch(error => { console.error(error); process.exit(1); });
