const assert = require('assert/strict');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '../miniapp');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const app = JSON.parse(read('app.json'));
const routes = app.subpackages.flatMap(pkg => pkg.pages.map(page => `${pkg.root}/${page}`));
['package-marketing/pages/bundles/index', 'package-marketing/pages/bundle-detail/index', 'package-marketing/pages/groups/index', 'package-marketing/pages/group-detail/index', 'package-marketing/pages/coupons/index', 'package-member/pages/points/index', 'package-member/pages/favorites/index', 'package-member/pages/reviews/index', 'package-member/pages/invoices/index', 'package-member/pages/stored-value/index'].forEach(route => assert(routes.includes(route), `${route} must be registered`));
const services = read('services/index.js');
['bundles', 'coupons', 'membership', 'favorites', 'reviews', 'invoices', 'storedValue'].forEach(name => assert(services.includes(`${name}:`), `${name} service must be exported`));
const checkout = read('package-trade/pages/checkout/index.js');
assert.match(checkout, /couponId/); assert.match(checkout, /discountAmountCent/); assert.match(checkout, /bundleId/); assert.match(checkout, /bundleQuantity/); assert.match(checkout, /groupsApi\.quote/); assert.match(checkout, /groupsApi\.join/); assert.match(checkout, /PAYMENT_NOT_CONFIGURED/);
const detail = read('package-trade/pages/order-detail/index.js');
assert.match(detail, /couponSnapshot/); assert.match(detail, /discountAmountCent/); assert.match(detail, /canReview/); assert.match(detail, /canInvoice/);
assert.match(detail, /paidSubtotalCent/);
assert.match(read('package-trade/pages/aftersale-apply/index.js'), /refundableAmountCent/);
const review = read('package-member/pages/reviews/index.js');
assert.match(review, /reviews\.eligible/); assert.match(review, /reviews\.uploadMedia/); assert.match(review, /orderItemId: item\.id/); assert.match(review, /idempotencyKey/);
const stored = read('package-member/pages/stored-value/index.wxml');
assert.match(stored, /储值与充值服务暂未开放/, 'stored-value page must state the real production capability status');
assert.doesNotMatch(stored, /<\s*(?:input|form|button)\b|bind(?:tap|submit)\s*=|充值意向|不会扣款，也不会增加余额/, 'an unavailable stored-value capability must not expose demo copy or operation controls');
console.log('marketing member contract test: passed');
