module.exports = {
  config: require('./config'),
  auth: require('./auth'),
  catalog: require('./catalog'),
  pricing: require('./pricing'),
  cart: require('./cart'),
  checkout: require('./checkout'),
  orders: require('./orders'),
  content: require('./content'),
  address: require('./address'),
  delivery: require('./delivery'),
  refunds: require('./refunds'),
  aftersales: require('./aftersales'),
  frequent: require('./frequent'),
  procurement: require('./procurement'),
  inquiries: require('./inquiries'),
  groups: require('./groups'),
  bundles: require('./bundles'),
  coupons: require('./coupons'),
  membership: require('./membership'),
  favorites: require('./favorites'),
  reviews: require('./reviews'),
  invoices: require('./invoices'),
  storedValue: require('./stored-value')
};
